title: "Data Discourse Digest"
author: "Glenn Benedict Montesclaros"
description: "Your hub for data insights, analysis, and technology trends." # A more engaging description

# Email / Social media user names used by the minima theme:
email: "data-insights-digest@googlegroups.com"
# twitter_username: "twitteruser"
# github_username: "githubuser"
# linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

theme: "minima"

minima:
  skin: dark

rss: rss
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: data-discourse-digest

url: my_website_url


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-image-size

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Posts

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

sass:
  style: compressed

skin: dark