title: "Data Discourse Digest"
author: "Admin"
description: "Your hub for data insights, analysis, and technology trends." # A more engaging description

# Email / Social media user names used by the minima theme:
email: "example@mail.com"
twitter_username: "twitteruser"
github_username: "githubuser"
linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

theme: "minima"

rss: rss

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

include:
  - css/custom.css

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Tech

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

sass:
  style: compressed

remote_theme: "minima"

skin: dark