services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --host 0.0.0.0
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
